name: Esquio Contrib Continous Deployment
on: 
  # push:
  #   tags:       
  #     - release-*  # Push events to release-* 
  push:
    branches: 
      - master
jobs:
  build:
    env:
      BUILD_CONFIG: Release

    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.0.0
      with:
        version: 3.1.100
    - name: dotnet build
      run: dotnet build Esquio.Contrib.sln -c $BUILD_CONFIG
    - name: dotnet test [FunctionalTests]
      run: dotnet test ./tests/FunctionalTests/FunctionalTests.csproj -c $BUILD_CONFIG --no-build
    - name: dotnet pack [Esquio.Toggles.GeoLocation]
      run: dotnet pack ./src/Esquio.Toggles.GeoLocation/Esquio.Toggles.GeoLocation.csproj -c $BUILD_CONFIG -o ./artifacts --no-build --include-source --include-symbols
    - name: dotnet pack [Esquio.Toggles.Http]
      run: dotnet pack ./src/Esquio.Toggles.Http/Esquio.Toggles.Http.csproj -c $BUILD_CONFIG -o ./artifacts --no-build --include-source --include-symbols
    - name: setup nuget
      uses: NuGet/setup-nuget@v1.0.2
      with:
        nuget-version: latest
    - name: push packages
      run: dotnet nuget push ./artifacts/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate