name: Esquio Contrib Nightly Build
on:
  schedule:
    - cron:  '0 6 * * *'
jobs:
  build:
    env:
      BUILD_CONFIG: Release

    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.0.0
      with:
        version: 3.1.100
    - name: dotnet build
      run: dotnet build Esquio.Contrib.sln -c $BUILD_CONFIG
    - name: dotnet test [FunctionalTests]
      run: dotnet test ./tests/FunctionalTests/FunctionalTests.csproj -c $BUILD_CONFIG --no-build
    - name: dotnet pack [Esquio.Toggles.GeoLocation]
      run: dotnet pack ./src/Esquio.Toggles.GeoLocation/Esquio.Toggles.GeoLocation.csproj -c $BUILD_CONFIG -o ./artifacts --version-suffix "-nightly"  --no-build --include-source --include-symbols
    - name: dotnet pack [Esquio.Toggles.Http]
      run: dotnet pack ./src/Esquio.Toggles.Http/Esquio.Toggles.Http.csproj -c $BUILD_CONFIG -o ./artifacts --version-suffix "-nightly"  --no-build --include-source --include-symbols
    - name: Publish nuget
      run: |
          for f in ./artifacts/*.nupkg
          do
            curl -vX PUT -u "Xabaril:${{ secrets.GITHUB_TOKEN }}" -F package=@$f https://nuget.pkg.github.com/Xabaril/
          done
      shell: bash